name: "Bug"
description: "Have you encountered a bug?"
labels: ["bug", "0. to triage"]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better your description is _(go 'here', click 'there'...)_ the fastest you'll get an _(accurate)_ answer.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: Expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Tell us what should happen
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Tell us what happens instead
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App version
      description: |
        See apps admin page, e.g. 0.5.3
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Any additional information related to the issue (ex. browser console errors, software versions).
